version = 1

test_patterns = ["**/*.test.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true
